In [1]:
import numpy as np

# Shallow Copy & Deep Copy

In [2]:
a = np.arange(1,6)
a

array([1, 2, 3, 4, 5])

* Stride is nothing but step size in array

#### Shallow Copy - The other variable shares the memory address of a variable 

In [3]:
b = a

In [4]:
b

array([1, 2, 3, 4, 5])

* Here assigning a to b is a shallow Copy
* But when we made any changes to original array it will create a new adress

In [5]:
x = a+1

In [6]:
x

array([2, 3, 4, 5, 6])

In [7]:
b = a[::2]

In [8]:
b

array([1, 3, 5])

* Here it is shallow copy, The changes will be made in header

* Initially (a)
### Metadata of a
| Headers   |           |
|-----------|-----------|
|   Shape   |   (5,)    |
|    ndim   |     1     |
|    Size   |      5    |
|    Stride |      1    |

* After assigning (b)
### Metadata of b
| Headers   |           |
|-----------|-----------|
|   Shape   |   (5,)    |
|    ndim   |     1     |
|    Size   |      5    |
|    Stride |      2    |

In [9]:
a = np.array([1,2,3,4,5])
b = a

# Function to check whether Memory Sharing happens or not

In [10]:
np.shares_memory(a,b)

True

In [11]:
b = a+1
np.shares_memory(a,b)

False

# Splitting in 1D

In [12]:
a = np.arange(9)
print(a)
b = np.split(a,3) # Equal Splits

[0 1 2 3 4 5 6 7 8]


In [13]:
b

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [14]:
b = np.split(a,(2,4,7)) # Split using Index
b

[array([0, 1]), array([2, 3]), array([4, 5, 6]), array([7, 8])]

# Splitting in 2D

In [15]:
x = np.arange(1,17).reshape(4,4)
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [16]:
np.split(x,2) #Divides into equal rows defaulty with axis = 0

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [17]:
np.hsplit(x,2) #Horizontal split

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [18]:
np.vsplit(x,2) #Vertical Split

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

# Stacking

In [19]:
a = np.arange(10)

In [20]:
np.vstack((a,a,a))

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [21]:
np.hstack((a,a,a))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1,
       2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
z = np.arange(9).reshape(3,3)
z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [23]:
np.vstack((z,z,z))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [24]:
np.hstack((z,z,z))

array([[0, 1, 2, 0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8, 6, 7, 8]])

In [25]:
np.concatenate((z,z,z),axis=0) #Stacking using concatenate function

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [26]:
g = np.arange(0,4)
g

array([0, 1, 2, 3])

In [27]:
g = np.vstack(g)
g

array([[0],
       [1],
       [2],
       [3]])

In [28]:
g = np.concatenate((g,g,g),axis=1)
g

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

# Broadcasting

In [29]:
a = np.arange(0,40,10)
a

array([ 0, 10, 20, 30])

In [30]:
a = np.vstack((a,a,a))

In [31]:
np.hstack((a,a,a))

array([[ 0, 10, 20, 30,  0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30,  0, 10, 20, 30]])

In [32]:
np.concatenate((a,a),axis=1)

array([[ 0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30]])

In [33]:
np.tile(a,(3,3))

array([[ 0, 10, 20, 30,  0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30,  0, 10, 20, 30]])

In [34]:
np.tile(a,(3,2))

array([[ 0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30]])

## Case 1 

In [35]:
a

array([[ 0, 10, 20, 30],
       [ 0, 10, 20, 30],
       [ 0, 10, 20, 30]])

In [36]:
v = np.vstack(a)
v

array([[ 0, 10, 20, 30],
       [ 0, 10, 20, 30],
       [ 0, 10, 20, 30]])

In [37]:
j = np.concatenate((v,v),axis =1)
j

array([[ 0, 10, 20, 30,  0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30,  0, 10, 20, 30]])

In [38]:
i = np.arange(0,3)
i

array([0, 1, 2])

In [39]:
j+i

ValueError: operands could not be broadcast together with shapes (3,12) (3,) 

## Case 2

In [40]:
j

array([[ 0, 10, 20, 30,  0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30,  0, 10, 20, 30]])

In [41]:
k = np.vstack((i,i,i,i))
k

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [42]:
j+k

ValueError: operands could not be broadcast together with shapes (3,12) (4,3) 

## Case 3

In [43]:
i

array([0, 1, 2])

In [44]:
v

array([[ 0, 10, 20, 30],
       [ 0, 10, 20, 30],
       [ 0, 10, 20, 30]])

In [45]:
o = np.concatenate((v,v,v),axis = 1)
o

array([[ 0, 10, 20, 30,  0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30,  0, 10, 20, 30]])

In [46]:
p = np.vstack((i,i,i,i))
p

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [47]:
p+o

ValueError: operands could not be broadcast together with shapes (4,3) (3,12) 

# Rule 1 : If two array differ in the number of dimesions, the shape of one with fewer dimensions is padded with ones on its leading (Left side)
# Rule 2 : If the shape of two arrays doesnot match in any dimensions, the array with shape equal to 1 is stretched to match the other shape.

In [48]:
array = np.arange(16).reshape(4,4)
array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [49]:
arr = np.array([0,1,2,3])

In [50]:
array+arr

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14],
       [12, 14, 16, 18]])

In [51]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [52]:
a.shape

(6,)

# Day 33 28-11-23

# Other function to increase the dimensions

In [58]:
b = np.expand_dims(a,axis=0)

In [60]:
print(b)
b.shape

[[0 1 2 3 4 5]]


(1, 6)

In [61]:
c = a[np.newaxis,:]
c.shape

(1, 6)

In [62]:
c

array([[0, 1, 2, 3, 4, 5]])

In [63]:
d = a[:,np.newaxis]
d

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [64]:
e = np.arange(6).reshape(2,3)
e

array([[0, 1, 2],
       [3, 4, 5]])

In [65]:
np.expand_dims(e,axis=0).shape

(1, 2, 3)

In [68]:
f = np.arange(6).reshape(2,3)
np.expand_dims(f,axis=2)

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

# Removing Dimensions

In [78]:
a = np.arange(5)
b = np.expand_dims(a,axis=1)
b

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [79]:
np.squeeze(b,axis=1)

array([0, 1, 2, 3, 4])

In [92]:
k = np.arange(12).reshape(1,12)
k

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [86]:
np.squeeze(k).shape

(12,)

### NumPy cannot remove the original dimension but can remove the fake dimension

In [93]:
np.squeeze(k,axis=1).shape

ValueError: cannot select an axis to squeeze out which has size not equal to one

In [94]:
a = np.arange(12).reshape(12,1,1)
a

array([[[ 0]],

       [[ 1]],

       [[ 2]],

       [[ 3]],

       [[ 4]],

       [[ 5]],

       [[ 6]],

       [[ 7]],

       [[ 8]],

       [[ 9]],

       [[10]],

       [[11]]])

In [95]:
np.squeeze(a,axis=-1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [98]:
np.squeeze(a,axis=-2)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [99]:
array = np.arange(10)

In [100]:
array2 = array.view

In [102]:
np.shares_memory(array2,array)

False

In [101]:
array3 = array.copy

In [103]:
np.shares_memory(array3,array)

False