#### Logical Functions

In [1]:
import numpy as np

In [2]:
a  = np.array([6,4,5,0])
b = np.array([4,3,2,1])

In [3]:
a < b

array([False, False, False,  True])

#### any function will return true if one condition is True otherwise it will return False

In [4]:
np.any(a<b)

True

#### all function will return False if any one condition is False

In [5]:
np.all(a>b)

False

#### Defining 2D Arrays

In [6]:
a = np.array([1,2,3,4,5,6,7,8,9,0,1,1,22,1,22,1])

In [7]:
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
b.shape

(2, 3)

In [9]:
a.size

16

#### Reshaping a 1D array into 2D Array

In [10]:
a = a.reshape(4,4)

In [11]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9,  0,  1,  1],
       [22,  1, 22,  1]])

In [12]:
d = np.arange(12).reshape(2,6)

In [13]:
d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

#### Transpose of a Matrix

In [14]:
d.T

array([[ 0,  6],
       [ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11]])

In [15]:
a.T

array([[ 1,  5,  9, 22],
       [ 2,  6,  0,  1],
       [ 3,  7,  1, 22],
       [ 4,  8,  1,  1]])

#### Quiz

In [16]:
c = np.array([1,2,3,4,5])
mask = (c%2 ==0)
c[mask] = -1
c

array([ 1, -1,  3, -1,  5])

#### Decreasing the Dimensions (Flatten)  2D to 1D

In [17]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9,  0,  1,  1],
       [22,  1, 22,  1]])

In [18]:
a.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9,  0,  1,  1, 22,  1, 22,  1])

#### Indexing/Slicing over arrays

In [19]:
a[[0,1,2],[0,1,2]]

array([1, 6, 1])

In [20]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9,  0,  1,  1],
       [22,  1, 22,  1]])

In [21]:
a[:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9,  0,  1,  1],
       [22,  1, 22,  1]])

In [22]:
a[0:2] # a[rows : columns]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [23]:
a[1:3,2:3]

array([[7],
       [1]])

#### Masking (Fancy indexing)

In [24]:
a[a>2].reshape(3,3)

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 22, 22]])

In [25]:
np.max(a,axis=1) # When axis = 0 it will consider Column, axis = 1 it will consider row

array([ 4,  8,  9, 22])

In [26]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9,  0,  1,  1],
       [22,  1, 22,  1]])

In [27]:
np.sum(a,axis=1)

array([10, 26, 11, 46])

In [28]:
np.sort(a) # Default axis is 1 Which is Row

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 0,  1,  1,  9],
       [ 1,  1, 22, 22]])

In [29]:
np.argmin(a) # argmin will return the index of min value

9

In [32]:
a = a.reshape(1,16)
np.argsort(a)

array([[ 9,  0, 10, 11, 13, 15,  1,  2,  3,  4,  5,  6,  7,  8, 12, 14]],
      dtype=int64)