# Assignment 1 - 15 11 23

#### 1. What is the result of the following expression in Python?

In [1]:
print(True==1)

True


#### 2. Write a program that takes the age of the user as input and tells them if they're old enough to ride a roller coaster. The minimum age to ride the roller coaster in this question is 13.

In [5]:
age = int(input("Enter your age:"))
if age >= 13:
    print("You are old enough to ride a roller coaster... Enjoy the ride !!")
elif age < 13:
    print("You are not old enough to ride a roller coaster")
else:
    print("Enter Correct value")

Enter your age: 66


You are old enough to ride a roller coaster... Enjoy the ride !!


#### 3.You are given 3 integer angles(in degrees) A, B and C of a triangle. You have to tell whether the triangle is valid or not. A triangle is valid if sum of its angles equals to 180.


In [6]:
a = int(input("Enter angle A of triangle:"))
b = int(input("Enter angle B of triangle:"))
c = int(input("Enter angle C of triangle:"))
sum_of_angles = a+b+c
if sum_of_angles == 180:
    print("The give angles form a triangle")
else:
    print("The given angles does not a triangle")

Enter angle A of triangle: 34
Enter angle B of triangle: 110
Enter angle C of triangle: 66


The given angles does not a triangle


#### 4. Write a program to input two numbers(A & B) from user and print the maximum element among A & B in each line

In [10]:
A = int(input("Enter number 1 :"))
B = int(input("Enter number 2 :"))
if A>B:
    print(f"Maximum Element is {A}\n")
elif B>A:
    print(f"Maximum Element is {B}\n")
elif A == B:
    print("Both are equal")
else:
    print("Enter correct number")

Enter number 1 : 3
Enter number 2 : 3


Both are equal


#### 5. Given the number N, Categorise the number according to following condition :
####   1. Odd-Positive
####   2. Odd-Negative
####   3. Even-Positive
####   4. Even-Negative

In [20]:
n = int(input("Enter number :"))

if n%2==1 and n>0:
    print("Odd-Positive")
elif n%2==1 and n<0:
    print("Odd-Negative")
elif n%2==0 and n>0:
    print("Even-Positive")
elif n%2==0 and n<0:
    print("Even-Negative")
else:
    print("Zero")

Enter number : -55


Odd-Negative


#### 6. Given a positive integer A, return an array of strings with all the integers from 1 to N. But for multiples of 3 the array should have “Fizz” instead of the number. For the multiples of 5, the array should have “Buzz” instead of the number. For numbers which are multiple of 3 and 5 both, the array should have "FizzBuzz" instead of the number.

In [25]:
a = int(input("Enter Positive Integer:"))
array = []
for i in range(1,a+1):
    if i%3 == 0:
        array.append('Fizz')
    elif i%5 == 0:
        array.append('Buzz')
    elif i%3 == 0 and i%5 == 0:
        array.append('FizzBuzz')
    else:
        array.append(i)
print(array)

Enter Positive Integer: 13


[1, 2, 'Fizz', 4, 'Buzz', 'Fizz', 7, 8, 'Fizz', 'Buzz', 11, 'Fizz', 13]


#### 7. Take an integer A as input. You have to tell whether A is divisible by both 5 and 11 or not.

In [27]:
A = int(input("Enter integer A:"))
if A%5 == 0 and A%11 == 0:
    print(f"Given number {A} is divisible by 5 and 11")
else:
    print(f"Given number {A} is not divisible by 5 and 11")

Enter integer A: 552


Given number 552 is not divisible by 5 and 11


#### 8. Write a program to print all even numbers from 1 to N where you have to take N as input from the user. Note: Use while-loop OR for-loop, according to session flow

###### Using while loop

In [38]:
n = int(input("Enter N:"))
even_array = []
while n>0:
    if n%2 == 0:
        even_array.append(n)
    n = n-1
print(even_array[::-1])

Enter N: 56


[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56]


###### Using For loop

In [40]:
n = int(input("Enter N:"))
even_array = []
for i in range(1,n+1):
    if i % 2 == 0:
        even_array.append(i)
print(even_array)

Enter N: 56


[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56]


#### 9. Write a program to print all odd numbers from 1 to N where you have to take N as input from the user. Here N is inclusive.


###### Using While Loop

In [41]:
n = int(input("Enter N:"))
even_array = []
while n>0:
    if n%2 != 0:
        even_array.append(n)
    n = n-1
print(even_array[::-1])

Enter N: 23


[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23]


###### Using for loop

In [42]:
n = int(input("Enter N:"))
even_array = []
for i in range(1,n+1):
    if i % 2 != 0:
        even_array.append(i)
print(even_array)

Enter N: 23


[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23]


#### 10. How many times will the following loop run?



In [2]:
# c = 0
# while c<=10:
#     print(c)
#     if c%2:
#         c-=1
#     else:
#         c+=1
# The loop will run infinite time
# Loop 1 : c = 0 go to if(False) then go to else block Then c value changes to 1 
# c = 1
# Loop 2 : c = 1 go to if(True) Then c value changes to 0
# c = 0
# Loop 3 : c = 0  ( Same as Loop 1 and then Loop 2 )
# It will run again and again and again

# Note : We can put break statement in while loop to exit loop

# Assignment 2 - 16 11 23 

#### Level 1

#### 1. Given two numbers A and B. Concatenate the two numbers and print it.

In [1]:
a = '4'
b = '5'
print(a+b)

45


#### 2. What is the result of the following expression in Python? print("1" == 1)

In [2]:
print("1" == 1)

False


#### 3.What is the output for the following statements?

In [3]:
x = 55 / 11
print(x)

5.0


#### 4. Write a program that asks the user to input their favorite programming language and output a specific string based on their answer. Based on the user minputs these are the outputs to be shown to the user.

In [9]:
pro = input("Enter your favorite programming language:")
pro = pro.lower()
if pro == 'python':
    print("Nice choice!")
elif pro == 'java':
    print("That's cool!")
elif pro == 'javascript':
    print("Okay so your are the web developer!")
elif pro == 'c++':
    print("Too old school")
else:
    print("I don't know that language")

Enter your favorite programming language: JaVa


That's cool!


#### 5. Write a program that takes a positive integer N as input from the user and prints all natural numbers from 1 to N, with each number followed by a space (including the last number).

In [13]:
n = int(input("Enter positive integer:"))
for i in range(1,n+1):
    print(i,end=" ")

Enter positive integer: 30


1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 

#### Level 2

#### 1. Given a number A and a digit B. Find the frequency of digit B in the number A. Return the frequency of digit B.

In [15]:
a = input("Enter number:")
b = input("Enter digit:")
count = 0
for i in a:
    if i == b:
        count+=1
print(f"{b} occured {count} times in {a}")


Enter number: 34445566543453
Enter digit: 3


3 occured 3 times in 34445566543453


#### 2. You are given lowercase string (A) and you have to return after reversing that.

In [16]:
a = 'string'
print(a[::-1])

gnirts


#### 3. You are given lowercase string (A) and you have to tell the count of vowels and consonants in it.

In [18]:
s = input("Enter string")
vowel_count = 0
cons_count = 0
for i in s:
    if i in ['a','e','i','o','u']:
        vowel_count += 1
    else:
        cons_count += 1
print(f"There are total of {vowel_count} vowels and {cons_count} consonants in given string {s}")

Enter string saiteja


There are total of 4 vowels and 3 consonants in given string saiteja


#### 4. You are given uppercase string (S) and you have to return a string that is the lower case form of S.
* Uppercase strings are those which have all letters in uppercase (Example: MACHINE)
* Lowercase strings are those which have all letters in lowercase (Example: machine)

In [21]:
s = 'MACHINE'
print(f"Upper Case: {s.upper()}")
print(f"Lower Case: {s.lower()}")

Upper Case: MACHINE
Lower Case: machine


#### 5. Given the temperature of a day in Degrees Celsius, convert this given temperature from Celsius to Fahrenheit. Complete the function to do so. Round the output up to 2 decimal places

In [23]:
def c_to_f(cel):
    return (cel * (9/5)) + 32
cel = int(input("Enter celsius degrees:"))
print(f"{cel} celsius degree is {round(c_to_f(cel),2)} in fahrenheit")

Enter celsius degrees: 44


44 celsius degree is 111.2 in fahrenheit


#### 6. Write a program to calculate the total amount if the principal amount, simple interest rate per annum, and time in the number of days are given. The simple interest rate per annum is provided as a percentage. Assuming that there are 365 days in a year, print the total amount rounded up to 2 decimal places.

In [1]:
def total_amount(p,i,t):
    i_dec = i / 100
    si = (p*i_dec*t)/365
    total_amount = round(p+si,2)
    return total_amount

p = float(input("Enter Principal Amount:"))
i = float(input("Enter Simple interest rate per annum:"))
t = int(input("Enter no of days are given:"))
print("==================================")
print(f"Principal Amount        | {p}")
print(f"Simple Interest         | {i}")
print(f"Time (in days)          | {t}")
print(f"Total Amount to be paid | {total_amount(p,i,t)}")

Enter Principal Amount: 50000
Enter Simple interest rate per annum: 3
Enter no of days are given: 365


Principal Amount        | 50000.0
Simple Interest         | 3.0
Time (in days)          | 365
Total Amount to be paid | 51500.0


#### 7. Write a program that takes the cost price of a vehicle as an argument and returns the road tax, that the vehicle owner has to pay according to the following criteria:

In [45]:
def road_tax(cost):
    if cost > 100000:
        print(f"Road tax to be paid : {round(cost*(20/100),2)}")
    elif cost > 75000 and cost<=100000:
        print(f"Road tax to be paid : {round(cost*(15/100),2)}")
    elif cost > 50000 and cost <= 75000:
        print(f"Road tax to be paid : {round(cost*(10/100),2)}")
    elif cost <=50000:
        print(f"Road tax to be paid : {round(cost*(5/100),2)}")
cost = int(input("Enter cost price of a vehicle:"))
road_tax(cost)

Enter cost price of a vehicle: 100000


Road tax to be paid : 15000.0


# Assignment 3 - 17 11 23

#### Level 1

#### 1. Write a program to create a function show_employee() using the following conditions.
* It should accept the employee’s name and salary and display both.
* If the salary is missing in the function call then assign default value 50,000 to salary


In [3]:
def show_employee(name,salary=50000):
    print(f"Employee Name: {name}")
    print(f"Employee Salary: {salary}")

name = input("Enter employee name:")
salary = int(input("Enter employee salary:"))
show_employee(name)

Enter employee name: sai
Enter employee salary: 60000


Employee Name: sai
Employee Salary: 50000


#### 2. Write a Python programme to Print First 10 natural numbers using while loop

In [9]:
# Approach 1
n = int(input("Enter range of natural numbers you want to get:"))
num = 1
while num<=n:
    print(num)
    num+=1

Enter range of natural numbers you want to get: 4


1
2
3
4


In [10]:
# Approach 2
n = int(input("Enter range of natural numbers you want to get:"))
while n>0:
    print(n)
    n -= 1

Enter range of natural numbers you want to get: 5


5
4
3
2
1


#### 3. Write a program to print multiplication table of a given number

In [14]:
n = int(input("Enter number for multiplication table:"))
for i in range(0,11):
    print(f"{n} * {i} = {n*i}")

Enter number for multiplication table: 10


10 * 0 = 0
10 * 1 = 10
10 * 2 = 20
10 * 3 = 30
10 * 4 = 40
10 * 5 = 50
10 * 6 = 60
10 * 7 = 70
10 * 8 = 80
10 * 9 = 90
10 * 10 = 100


#### 4. Write a program to count the total number of digits in a number using a while loop


In [18]:
n = int(input("Enter number:"))
count = 0
while n>0:
    n //= 10
    count += 1
print(count)

Enter number: 987452631


9


#### 5. Given two integer numbers, return their product only if the product is equal to or lower than 1000. Otherwise, return their sum.

In [21]:
a = int(input("Enter integer number 1:"))
b = int(input("Enter integer number 2:"))
if a*b <= 1000:
    print(a*b)
else:
    print(a+b)

Enter integer number 1: 400
Enter integer number 2: 400


800


#### 6. Write a Python programme to calculate Income tax of an employee following the below criteria.
* 5 Lakhs - 10%
* 5 -7 Lakhs - 20%
* 7-10 Lakhs - 30%
* \>15 Lakhs - 40%

In [25]:
salary = int(input("Enter the total earnings:"))
if salary == 500000:
    print(f"Income Tax to be paid: {salary*0.1}")
elif salary >= 500000 and salary <= 700000:
    print(f"Income Tax to be paid: {salary*0.2}")
elif salary >= 700000 and salary <= 1000000:
    print(f"Income Tax to be paid: {salary*0.3}")
elif salary > 1500000:
    print(f"Income Tax to be paid: {salary*0.4}")

Enter the total earnings: 500000


Income Tax to be paid: 50000.0


#### 8. Write a python programme to Count all letters, digits, and special symbols from a given string

In [56]:
string = input("Enter string here:")
digit = 0
letters = 0
special = 0
for i in string:
    if i.isdigit():
        digit += 1
    elif i.isalpha():
        letters += 1
    else:
        special += 1
print(f"There are \n{digit} digits\n{letters} letters\n{special} special characters")

Enter string here: &8*4#kgf


There are 
2 digits
3 letters
3 special characters


#### Level 2

#### 1. Write a program to iterate the first 10 numbers, and in each iteration, print the sum of the current and previous number.


In [33]:
# It is an example of Fibonacci Series
first = 0
second = 1
for _ in range(10):
    n1 = first + second
    first = second
    second = n1
    print(n1,end=" ")

1 2 3 5 8 13 21 34 55 89 

#### 2. Write a program to accept a string from the user and display characters that are present at an even index number.

In [34]:
str = input("Enter the string:")
for i in str:
    if str.index(i) % 2 == 0:
        print(i)    

Enter the string: string


s
r
n


#### 3. Given two list of numbers, write a program to create a new list such that the new list should contain odd numbers from the first list and even numbers from the second list

In [36]:
list1 = list(map(int,input("Enter numbers of list 1 separated by space:").split(" ")))
list2 = list(map(int,input("Enter numbers of list 2 separated by space:").split(" ")))
new_odd = []
new_even = []
for i in list1:
    if i % 2 != 0:
        new_odd.append(i)
for j in list2:
    if j % 2 == 0:
        new_even.append(j)

print("Odd numbers from list 1:",new_odd)
print("Even numbers from list 2:",new_even)

Enter numbers of list 1 separated by space: 3 5 7 1 4
Enter numbers of list 2 separated by space: 7 8 9 11 2 3


Odd numbers from list 1: [3, 5, 7, 1]
Even numbers from list 2: [8, 2]


#### 4. Write a program to add two lists index-wise. Create a new list that contains the 0th index item from both the list, then the 1st index item, and so on till the last element. any leftover items will get added at the end of the new list.

In [47]:
list1 = list(input("Enter numbers of list 1 separated by space:").split(" "))
list2 = list(input("Enter numbers of list 2 separated by space:").split(" "))
print("List1:",list1)
print("List2:",list2)
new_list = []
min_length = min(len(list1), len(list2))
for i in range(min_length):
    new_list.append(list1[i] + list2[i])

if len(list1) > len(list2):
    new_list.extend(list1[min_length:])
else:
    new_list.extend(list2[min_length:])

print("Output:",new_list)

Enter numbers of list 1 separated by space: M na i Ri
Enter numbers of list 2 separated by space: y me s A 4 3 5 t h jji


List1: ['M', 'na', 'i', 'Ri']
List2: ['y', 'me', 's', 'A', '4', '3', '5', 't', 'h', 'jji']
Output: ['My', 'name', 'is', 'RiA', '4', '3', '5', 't', 'h', 'jji']


#### 5. Write a Python program to return a new set with unique items from both sets by removing duplicates.


In [49]:
set1 = set(map(int,input("Enter numbers of Set1 separated by space:").split(" ")))
set2 = set(map(int,input("Enter numbers of Set2 separated by space:").split(" ")))
new_set = set1.union(set2)
print(new_set)

Enter numbers of Set1 separated by space: 3 4 5 6 8 9
Enter numbers of Set2 separated by space: 2 3 4 6 99 9


{2, 3, 4, 5, 6, 99, 8, 9}


#### 6. Write a program to unpack the following tuple into four variables and display each variable

In [50]:
tuple = tuple(input("Enter 4 tuple elements separated by space:").split(" "))
(var1, var2, var3, var4) = tuple
print(var1)
print(var2)
print(var3)
print(var4)

Enter 4 tuple elements separated by space: 4 5 6 7


4
5
6
7


#### 7. Write a function to return True if the first and last number of a given list is the same. If numbers are different then return False.

In [51]:
def check(num):
    if num[0] == num[-1]:
        return True
    else:
        return False

num = input("Enter number:")
check(num)

Enter number: 45784


True

#### 8. Write a program to check if the given number is a palindrome number.
* A palindrome number is a number that is the same after reverse. For example, 545, is the palindrome numbers

In [55]:
n = input("Enter number:")
if n == n[::-1]:
    print(f"{n} is a palindrome")
else:
    print(f"{n} is not a palindrome")

Enter number: bob


bob is a palindrome


# Assignment 4 - 20 11 23 (NumPy)

In [19]:
import numpy as np

#### 1. Which of the following option(s) can add 1 to each element of array A?

#### A = np.array([2, 0, 1, 9, 1, 1, 1, 0, 3, 5])
##### a) A+1
##### b) list(map(lambda x:x+1, A))
##### c) [x+1 for x in A]
##### d) A+"1"

* Options a,b,c are correct but option d will throw an error

#### 2. Given an array, return the shape and dimension of the array.

In [20]:
A = np.array([2, 0, 1, 9, 1, 1, 1, 0, 3, 5])
print(A.ndim)
print(A.shape)

1
(10,)


#### 3 a)Write the code using np.arange() to get all even numbers between 21 and 70, (70 inclusive)

In [21]:
np.arange(22,71,2)

array([22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54,
       56, 58, 60, 62, 64, 66, 68, 70])

#### 3 b) Write the code using np.arange() to get all odd numbers between 20 and 71. (71 inclusive)

In [22]:
np.arange(21,72,2)

array([21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53,
       55, 57, 59, 61, 63, 65, 67, 69, 71])

#### The correct option for 3 question is a,d

#### 4. Given the start, end, and the stepsize return a numpy array sequence in given range with the specified stepsize.

In [23]:
start = int(input("Enter number to start from:"))
end = int(input("Enter number to end:"))
step = int(input("Enter step size:"))
np.array(range(start,end,step))

Enter number to start from: 4
Enter number to end: 200
Enter step size: 5


array([  4,   9,  14,  19,  24,  29,  34,  39,  44,  49,  54,  59,  64,
        69,  74,  79,  84,  89,  94,  99, 104, 109, 114, 119, 124, 129,
       134, 139, 144, 149, 154, 159, 164, 169, 174, 179, 184, 189, 194,
       199])

#### 5. Which option is correct about the output of the following code snippet?

In [24]:
x = np.array([-5, 9 , 20 , 25, -3, 5, 16, 10,-8])
x[(x >= -5) & (x <= 15)] *= -1
print(x)

[  5  -9  20  25   3  -5  16 -10  -8]


#### Correct option is b) Given code will change the sign of all the numbers in range [-5, 15] in x.